replicatedhq/replicated

.gitignore, Dockerfile, Makefile, README.md, client/channel.go, client/channel_test.go, client/client.go, client/client_test.go, client/release.go, client/release_test.go, glide.lock, glide.yaml
Generate models from the Vendor API's Swagger spec. The generated http transport code was too messy to be useful.
The tests are integration tests, not unit tests. Perhaps they should be in a separate package?
=> Client for release and channel management

cli/cmd/channel_inspect.go, cli/cmd/channel_rm.go, cli/cmd/release_inspect.go, cli/cmd/release_promote.go, cli/cmd/release_update.go, cli/print/channel_releases.go, cli/print/channels.go, cli/print/release.go, cli/print/releases.go, cli/print/util.go
Short help for release inspect and channel inspect should show required
paramters.
Use errors.New instead of fmt.Errorf unless formatting.
=> CH440: Use RFC3339 for all printed times.

README.md, cli/cmd/release_create.go, cli/cmd/release_update.go, cli/cmd/root.go, cli/cmd/runner.go, cli/main.go, cli/test/channel_adoption_test.go, cli/test/channel_counts_test.go, cli/test/channel_create_test.go, cli/test/channel_inspect_test.go, cli/test/channel_ls_test.go, cli/test/channel_releases_test.go, cli/test/channel_rm_test.go, cli/test/release_create_test.go, cli/test/release_inspect.go, cli/test/release_ls_test.go, cli/test/release_promote_test.go, cli/test/release_update_test.go
This is useful on Windows where the "$(< replicated.yml)" syntax is not supported.
It allows for `type replicated.yml | replicated release create create --promote Unstable --yaml -`
=> Allow reading yaml from stdin

install.sh
* Harmonize the `curl` invocations; it was weird having one long-form and the other -s
* Add `--fail` to the curl invocations; emitting an error document will almost never be the desired outcome
* Use the less verbose `\d` grep since `-E`xtended syntax was already switched on
* Fix the erroneous `[[ a =~ b ]]` invocation
* Accept an argument of the directory into which `replicated` will go, giving precedence to any `$replicated_bindir` env-var
* Sanity check said directory
* Avoid writing out an intermediary tar file, streaming it through is enough to extract the one binary
=> Clean up the install.sh

cli/cmd/release_lint.go, cli/cmd/root.go, cli/print/lint.go, client/release.go, pkg/platformclient/client.go, pkg/platformclient/release.go, pkg/shipclient/client.go, pkg/shipclient/release.go, pkg/types/release.go
This adds a new command:
`replicated release lint --yaml "$(cat ./ship.yaml)"`
If the current app (`REPLICATED_APP`) is a ship app, it will use the API token to send the YAML to the GraphQL endpoint specified, and lint, returning errors.
Linting on the server side is: a) easier for now (the linter is JS, this project is go).  and b) allows for linting of dynamic dependencies (github assets, registry credentials, etc)
=> Linting for ship apps

pacts/replicated-cli-vendor-graphql-api.json, pkg/shipclient/release.go, pkg/shipclient/release_test.go
One test is as stripped down as I can make the request, while the other uses the actual client code
=> add pact tests for ship release promotion

.travis.yml, Makefile
This way we keep the 'best' of both worlds - we don't need to release this in order to publish the new pact tests, but we avoid cluttering up the pact test matrix with every commit that gets pushed.
Tags will have versions like `v0.10.0`, untagged versions like `v0.10.0-postrelease`.
=> use a better versioning system for pact tests

.goreleaser.yml, Gopkg.lock, Makefile, cli/cmd/root.go, cli/cmd/version.go, pkg/version/build.go, pkg/version/run.go, pkg/version/version.go, pkg/version/version_test.go, vendor/github.com/stretchr/testify/require/doc.go, vendor/github.com/stretchr/testify/require/forward_requirements.go, vendor/github.com/stretchr/testify/require/require.go, vendor/github.com/stretchr/testify/require/require.go.tmpl, vendor/github.com/stretchr/testify/require/require_forward.go, vendor/github.com/stretchr/testify/require/require_forward.go.tmpl, vendor/github.com/stretchr/testify/require/requirements.go
this allows `replicated version` to return results
For instance:
```
{
"version": "v0.10.0-27-gf526188c",
"git": "f526188",
"buildTime": "2019-07-02T23:05:52Z",
"go": {
"version": "go1.12.6",
"compiler": "gc",
"os": "darwin",
"arch": "amd64"
}
}
```
`version` is derived from `git describe`, so releases will properly respond with `v0.11.0` or whatever the current version happens to be. Prerelease tests will receive the `<previous-tag>-<commits-since-tag>-<previous-commit-sha>` format.
=> version cmd redux

.goreleaser.yml
I am unable to repro this locally, but right now if you `docker run` any of the images here you get an error around `not found` which I think has to do with trying to run these on musl/alpine https://hub.docker.com/r/replicated/vendor-cli/tags?page=1&ordering=last_updated
=> static build for alpine support

pacts/replicated-cli-vendor-api.json, pacts/replicated-cli-vendor-graphql-api.json
For some reason having a newer version of the golang:1.12 image results in different output
=> add 'metadata: null' to pact jsons

cli/cmd/entitlements_getcustomerrelease.go, cli/cmd/release_create.go, cli/cmd/runner.go, cli/test/util.go, client/channel.go, pkg/kotsclient/channel.go, pkg/kotsclient/client.go
Now you can do something like
```shell
replicated release create \
--yaml-dir=./manifests/ \
--promote=${GITHUB_BRANCH} \
--ensure-channel
```
And it will promote the release to the `${GITHUB_BRANCH}` channel, creating that channel if it does not exist yet.
=> add --ensure-channel flag for kots apps

cli/cmd/channel_adoption.go, cli/cmd/channel_counts.go, cli/cmd/channel_create.go, cli/cmd/channel_inspect.go, cli/cmd/channel_releases.go, cli/cmd/channel_rm.go, cli/cmd/collector_create.go, cli/cmd/collector_inspect.go, cli/cmd/collector_ls.go, cli/cmd/collector_promote.go, cli/cmd/collector_update.go, cli/cmd/collectors.go, cli/cmd/entitlements.go, cli/cmd/entitlements_definefields.go, cli/cmd/entitlements_getcustomerrelease.go, cli/cmd/entitlements_setvalue.go, cli/cmd/release_inspect.go, cli/cmd/release_lint.go, cli/cmd/root.go
Acceptance: Only the following commands show when typing the --help command (at root) or the <command> --help command.
release ls
release create
release create --promote
release promote
release update
channel ls
customer ls
customer create
=> Hide the functionality shown in Vendor CLI so that it only shows what is usable with KOTS applications.

cli/cmd/release_create.go, cli/cmd/release_lint.go, cli/cmd/runner.go, cli/print/lint.go, client/release.go, pkg/kotsclient/client.go, pkg/kotsclient/release_lint.go, pkg/shipclient/release.go, pkg/types/release.go
```
$ go run ./cli release lint --yaml-dir ../kots-sentry/manifests
RULE                           TYPE    START LINE    MESSAGE
config-option-password-type    warn    64            Config option "external_postgres_secretname" should have type "password"
```
For a dir with this malformed yaml file and nothing else:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: sentry
labels:
app: sentr
{
data:
config.yml: |-
...While a lot of configuration in Sentry can be changed via the UI, for all
```
```
$ go run ./cli release lint --yaml-dir ./manifests
RULE                TYPE     START LINE    MESSAGE
msg-yaml-invalid    error    8             missed comma between flow collection entries at line 9, column 13:
config.yml: |-
^
preflight-spec       warn                  Missing preflight …
```
=> implement kots release linting

cli/cmd/release_lint.go, cli/cmd/release_update.go, cli/cmd/runner.go, cli/main.go
CC @austinchambers  @aj-jester  @Vwampage for visibility
```
$ go run ./cli release lint --yaml-dir=../kots-sentry/manifests
RULE                           TYPE    LINE    MESSAGE    
config-option-password-type    warn    65      Config option "external_postgres_secretname" should have type "password"
$ echo $?
0
```
Failure with warning
```
$ go run ./cli release lint --yaml-dir=../kots-sentry/manifests --fail-on=warn
RULE                           TYPE    LINE    MESSAGE    
config-option-password-type    warn    65      Config option "external_postgres_secretname" should have type "password"
Error: One or more errors of severity "warn" or higher were found
$ echo $?
1
```
Unsupported threshold:
```
$ go run ./cli release lint --yaml-dir=../kots-sentry/manifests --fail-on=lol
Error: …
```
=> another refactor, add --fail-on flag, fix double-printing errors

cli/print/lint.go, client/release.go, pkg/types/release.go
```
RULE                           TYPE    FILENAME                    LINE    MESSAGE
replicas-1                     info    cron-deployment.yaml        11      Found Replicas 1
replicas-1                     info    redis-deployment-2.yaml     12      Found Replicas 1
replicas-1                     info    web-deployment.yaml         11      Found Replicas 1
container-resources            info    init-job.yaml               16      Missing container resources
container-resources            info    redis-deployment-2.yaml     24      Missing container resources
container-resources            info    redis-statefulset.yaml      24      Missing container resources
container-resources            info    usercreate-job.yaml         16      Missing container resources …
```
=> add filenames to linting

README.md
Use spaces instead of `=` character for replicated release command.
=> Fix Format of replicated command

cli/cmd/release_update.go
Uses the correct variable name to get the `--yaml-dir` argument. Previously it would always try to walk an empty string path.
Fixes #101.
Signed-off-by: Michael Smith <michael.smith@puppet.com>
=> Fix 'release update --yaml-dir'

cli/cmd/collector_inspect.go, cli/cmd/installer.go, cli/cmd/installer_create.go, cli/cmd/installer_ls.go, cli/cmd/release_create.go, cli/cmd/root.go, cli/cmd/runner.go, cli/print/installers.go, cli/test/cli_test.go, client/client.go, client/installer.go, pkg/kotsclient/app.go, pkg/kotsclient/client.go, pkg/kotsclient/installer.go, pkg/kotsclient/kotsclient_test.go, pkg/kotsclient/release_test.go, pkg/platformclient/client_test.go, pkg/shipclient/shipclient_test.go, pkg/types/installer.go, pkg/util/parseTime.go, pkg/util/parseTime_test.go
Listing installers:
$ replicated installer ls
SEQUENCE    CREATED                 ACTIVE_CHANNELS
2           2020-03-09T22:01:04Z    Stable
1           2019-12-03T00:12:31Z    Config-collelct,Beta,Unstable
Creating/promoting installers
$ replicated installer create --promote Unstable --yaml-file ~/tmp/kurl-installer.yaml
SEQUENCE: 15
Channel VEr0nhJBBUdaWpPvOIK-SOryKZEwa3Mg successfully set to release 15
Listing again
$ replicated installer ls
SEQUENCE    CREATED                 ACTIVE_CHANNELS
15          2020-03-13T22:55:52Z    Unstable
14          2020-03-13T22:38:46Z
13          2020-03-13T21:10:51Z    dextest
12          2020-03-12T17:28:16Z    dextest2
11          2020-03-10T01:16:52Z
10          2020-03-10T01:16:17Z
9           2020-03-10T01:15:49Z
8           2020-03-10T01:13:02Z …
=> Adding "installer ls" and "installer create" commands to CLI

install.sh
Wrapping this in a function allows safe usage of `curl | bash`, as it ensures that the script is not executed until the _entire_ script is downloaded.
=> feat: wrap main body in function

pkg/enterpriseclient/auth.go, pkg/enterpriseclient/auth_test.go, pkg/enterpriseclient/client.go
the old signature format is also still provided to prevent breakage, and an exported function has been created to validate signatures
=> include a timestamp and nonce in signed enterprise requests

cli/cmd/customer_create.go, cli/print/customers.go, client/customer.go, pkg/kotsclient/customer_create.go, pkg/kotsclient/customer_license_download.go, pkg/kotsclient/customer_list.go, pkg/platformclient/app.go, pkg/platformclient/channel.go, pkg/platformclient/collector.go, pkg/platformclient/license.go, pkg/platformclient/release.go, pkg/types/customer.go
```
replicated customer ls
replicated customer create --channel Unstable --name SomeBigBank --expires-in 720h 
replicated customer download-license --customer SomeBigBank --output ./license.yaml
```
=> move all customer management to V3 API

Makefile, cli/cmd/channel_create.go, cli/cmd/channel_inspect.go, cli/cmd/channel_ls.go, cli/cmd/customer_create.go, cli/cmd/customer_download_license.go, cli/cmd/release_create.go, cli/cmd/release_promote.go, cli/cmd/root.go, cli/cmd/runner.go, cli/print/channel_attributes.go, cli/print/logger.go, cli/test/kots_release_create_test.go, cli/test/util.go, client/channel.go, client/client.go, go.mod, go.sum, pkg/kotsclient/app.go, pkg/kotsclient/app_create.go, pkg/kotsclient/channel.go, pkg/kotsclient/client.go, pkg/kotsclient/customer_create.go, pkg/kotsclient/customer_license_download.go, pkg/kotsclient/customer_list.go, pkg/platformclient/channel.go, pkg/platformclient/client.go, pkg/shipclient/channel.go, pkg/types/channel.go
this uses go template `with` to skip these on non-kots apps. I really want these install scripits to be sent down from the server side, but for now they are built by the client in vendor.replicated.com, so we'll build them in the client here as well.
```
$ replicated channel inspect dextestxxxxx
ID:             _-0LiRWGjBG2-VtJIr0F127QPiuR7T6M
NAME:           dextestxxxxx
DESCRIPTION:
RELEASE:        11
VERSION:        0.0.1
EXISTING:
curl -fsSL https://kots.io/install | bash
kubectl kots install kots-dex/dextestxxxxx
EMBEDDED:
curl -fsSL https://k8s.kurl.sh/kots-dex-dextestxxxxx | sudo bash
AIRGAP:
curl -fsSL -o kots-dex-dextestxxxxx.tar.gz https://k8s.kurl.sh/bundle/kots-dex-dextestxxxxx.tar.gz
tar xvf kots-dex-dextestxxxxx.tar.gz
sudo bash ./install.sh airgap
```
Other stuff
---------- …
=> add installer commands to kots channel inspect

.gitignore, cli/cmd/release_promote.go, pkg/kotsclient/app.go
Small change so that the promote command:
`replicated release promote 14 todd --version 0.0.14`
will output human readable channel name:
`Channel todd successfully set to release 14`
instead of the current:
`Channel 1lTUjrHZchcezP6lUWhBwrdMcbg successfully set to release 14`
=> Todd fix promote channel

cli/cmd/collector_create.go, cli/cmd/collector_update.go, cli/cmd/installer_create.go, cli/cmd/release_create.go, cli/cmd/release_update.go, cli/test/kots_installer_create_test.go, cli/test/release_create_test.go, cli/test/release_update_test.go
Partial fix for this [issue](https://app.clubhouse.io/replicated/story/34321/replicated-vendor-cli-cannot-promote-installer-releases-to-a-channel). Added an error case when users pass a yaml file as the argument to the `--yaml` flag. Also updated some of the error handling (using `pkg/errors` exclusively instead of mixing it with Golang errors).
=> fix: return an error when a filename is used with the yaml flag

.goreleaser.yml
Some changes to fix the binary name from `cli` to `replicated`?
=> Fixed binary name?

cli/cmd/app_delete.go, cli/cmd/installer_create.go, cli/cmd/release_create.go, cli/cmd/release_download.go, pkg/kots/release/save.go, pkg/kots/release/save_test.go, pkg/kots/release/testdata/save/input/release.json, pkg/kots/release/testdata/save/want/app/example-configmap.yaml, pkg/kots/release/testdata/save/want/archive.tgz, pkg/kots/release/testdata/save/want/example-service.yaml, pkg/kots/release/testdata/save/want/kots-app.yaml, pkg/kots/release/testdata/save/want/kots/kots-config.yaml, pkg/kots/release/types/types.go, pkg/logger/logger.go
Application archives can have nested directories, and directory children in the application archive are structured objects, not strings.
The main change is that
```
Children []string `json:"children"`
```
became
```
Children []KotsSingleSpec `json:"children"`
```
And recursion was added when saving downloaded archives.
=> Download command supports releases with directories

cli/cmd/channel_counts.go, cli/cmd/channel_create.go, cli/cmd/channel_inspect.go, cli/cmd/channel_ls.go, cli/cmd/channel_releases.go, cli/cmd/customer_create.go, cli/cmd/release_create.go, cli/cmd/release_promote.go, cli/print/channel_attributes.go, client/channel.go, pkg/kotsclient/channel.go, pkg/kotsclient/channel_test.go, pkg/shipclient/channel.go, pkg/types/channel.go
See https://app.shortcut.com/replicated/story/63010/replicated-cli-channel-inspect-command-shows-inconsistent-channel-info
Inconsistency is due to `channel inspect` using a `types.Channel` (which has an `InstallCommands` field) for output in the Name lookup case and a `channels.AppChannel` (which does not have `InstallCommands`) for output in the ID lookup case.
1. Move install commands text from `types.Channel.InstallCommands` to template in `cli.print.ChannelAttrs()`. Commands are strictly derived from app and channel attributes (currently just the slugs) so don't really belong as additional channel attributes.
2. Make `client.GetChannel()` return `(*types.Channel, error)` instead of `(*channels.AppChannel, []channels.ChannelRelease)` for consistency with `ListChannel`. This implies …
=> Inconsistent channel info 63010

cli/cmd/cluster_create.go, pkg/kotsclient/cluster_create.go
This continues the `cluster` subcommand for reliability matrix.
1. `cluster create` prints the output row from the clusters ls command to get the id, etc
2. version uses the `v` prefix
=> Add additional cluster management crud

cli/cmd/login.go, cli/cmd/root.go, cli/cmd/runner.go, go.mod, go.sum, pkg/credentials/credentials.go, pkg/credentials/fetch.go, pkg/credentials/types/types.go
Adds a `replicated login` command to make it easier to authenticate and get started with the replicated CLI. Will not overwrite existing `REPLICATED_API_TOKEN` credentials that are stored.
(internal story: https://app.shortcut.com/replicated/story/74465/add-a-replicated-login-command-to-the-cli)
=> Add replicated login command

.github/workflows/release.yml
One more layer of indirection was required to get back to the actual tag SHA
Also fixed the release event. `create` cannot be filtered; this would have fired any time someone created any tag or branch. `push` is the correct event to use here.
=> fix finding previous release sha

cli/cmd/api.go, cli/cmd/api_get.go, cli/cmd/api_post.go, cli/cmd/api_put.go, cli/cmd/root.go, cli/cmd/runner.go, pkg/kotsclient/api.go, pkg/platformclient/client.go
This is a quick implementation of a `replicated api <path>` command that works for GET methods today, using the CLI creds.
Exmaple
```
% make build && ./bin/replicated api get v3/apps | jq | more
go build \
-ldflags " -X github.com/replicatedhq/replicated/pkg/version.version=v0.44.0-22-g65b01545 -X github.com/replicatedhq/replicated/pkg/version.gitSHA=`git rev-parse HEAD` -X github.com/replicatedhq/replicated/pkg/version.buildTime=`date -u +"%Y-%m-%dT%H:%M:%SZ"` " \
-o bin/replicated \
cli/main.go
Update available: v0.46.0
To automatically upgrade, run "replicated version upgrade"
{
"apps": [
{
"id": "cut",
"teamId": "cut",
"name": "Slackernews",
"created": "2022-06-02T20:53:54Z",
"description": "",
"isArchived": false,
"slug": "slackernews",
"renamedAt": null,
"isKotsApp": true, …
```
=> Add an 'api get' command

cli/cmd/channel_inspect.go, cli/cmd/runner.go
Uses different variable as others have default `table`
=> Fixes #256 Channel Inspect default output format

cli/cmd/release_create.go, cli/cmd/release_promote.go, cli/cmd/release_update.go
Only validate that --lint flag is not used with Builders app releases. All other KOTS application inputs are allowed. Version label will be validated by the API.
=> Relax validation for Builders apps

cli/cmd/customer_download_license.go, cli/print/channel_attributes.go, cli/print/clusters.go, cli/print/customers.go, pkg/credentials/fetch.go
[SC 77671](https://app.shortcut.com/replicated/story/77671/don-t-show-sign-at-the-end-of-the-replicated-cluster-ls-command-when-no-clusters-are-available)
=> Add newline to ouput

cli/cmd/cluster_kubeconfig.go, cli/cmd/runner.go
Allows use to get kubeconfig by id or name of cluster (id as a position arg remains the default).  also allows writing the kubeconfig to a file instead of merging, if desired.
=> Options to get kubeconfig

cli/cmd/cluster_create.go, cli/cmd/cluster_ls.go, cli/cmd/runner.go, cli/print/clusters.go
Added a watch flag to cluster ls that compares the cluster list every 2 seconds and prints the changes made to the CLI. Adding new clusters, removing clusters, or a cluster being changed or updated will all trigger a new printing of that cluster.
=> added watch command to cluster ls

cli/cmd/release_create.go
https://app.shortcut.com/replicated/story/81185/ensure-yaml-dir-target-is-a-directory-before-uploading-release
=> Require arg of yaml-dir command line parameter to be a file

cli/cmd/release_create.go, cli/cmd/release_lint.go, cli/cmd/runner.go, client/release.go, pkg/kotsclient/release_lint.go
Relevant linter PR: https://github.com/replicatedhq/kots-lint/pull/161
```
$ ./bin/replicated release lint --chart testchart-without-labels-16.2.2.tgz 
Update available: v0.48.0
To automatically upgrade, run "replicated version upgrade"
RULE                          TYPE    FILENAME    LINE    MESSAGE
preflight-spec                warn                            Missing preflight spec                       
informers-labels-not-found    warn                            No informer labels found on any resources    
```
```
$ ./bin/replicated release lint --yaml-dir ./builders-files
Update available: v0.48.1
To automatically upgrade, run "replicated version upgrade"
RULE    TYPE    FILENAME    LINE    MESSAGE
preflight-spec                warn                            Missing preflight …
```
=> Allow linting Builders apps

cli/cmd/customer_create.go, pkg/kotsclient/customer_create.go
Don't require a channelid (name) when creating a customer if the customer is a "test" type. (this is also enforced in the api)
=> Allow customers assigned to test customers to not have a channel

cli/cmd/customer_ls.go, cli/cmd/runner.go, cli/print/customers.go, client/customer.go, pkg/kotsclient/customer_list_by_app_version.go, pkg/types/customer.go, pkg/types/instance.go
The API already provides instance data including the application version. However, its cumbersome to find which instances or customers that are running a specific software release. This subcommand allows you to use the CLI to report on customers (and their instances), which are running a specific version.
**Use Case**
A vendor wants to know which of their customers and instances are running a specific version of their software.
**Implementation**
- Use the existing Vendor API /v3/app/%s/customers? route to retrieve all customers
- Iterate the response json, looking at which customers are running the appID specified in the 
- Search the Instance versionHistory.VersionLabel for matching instances of the specified version
- Print the results to screen either table or json format (depending …
=> Adds functionality to display customers and their instances for a specific app version

cli/cmd/cluster_prepare.go, pkg/kotsclient/release.go, pkg/types/release.go
- use charts struct from vendor-api
https://github.com/replicatedhq/vandoor/pull/3891
`ChartNames` was changed to `Charts` which breaks the `cluster prepare` cmd
https://github.com/replicatedhq/vandoor/pull/3891/files#diff-352bc1b2581837f7b0ebd288c4249b22d7a67891f98956d5cc971f1ea9cc6a63R82-R84
=> fix: chart prepare cmd

cli/cmd/cluster_create.go, cli/cmd/cluster_prepare.go, cli/cmd/runner.go, cli/print/clusters.go, pkg/kotsclient/cluster_create.go, pkg/types/cluster.go
This starts to use the new r1.<size> instance types instead.
Before this PR (and other supporting PRs), VM based instances required a vcpus and memory flag while cloud instances required an instance-type flag. This was a bad experience and worse since we only supported powers of 2 for vcpus and balanced (1 by 4) instance specs. Now we have standard instance types and a consistent API and CLI to request VM instances.
=> remove vcpus and memory flags

cli/cmd/cluster_prepare.go, cli/cmd/cluster_prepare_test.go, cli/print/release.go, client/release.go, pkg/kots/release/save.go, pkg/kots/release/save_test.go, pkg/kotsclient/release.go, pkg/types/release.go
validate release status during cluster prepare cmd
- using chart status from release, validate if charts are pushed successfully before installing the helm charts
https://github.com/replicatedhq/vandoor/blob/11764ef0728ee481aa19a8e95709b655252a0925/vendor-api/kots/release/release.go#L34-L41
- if a release chart is in `pushing` or `unkown` state, sleep for 2 seconds and retry the status check.
- exit and return error if  release chart are not in status `pushed` within `(10 * no of charts) seconds`
=> feat: validate release status during cluster prepare cmd

cli/cmd/cluster_rm.go, cli/cmd/runner.go, pkg/kotsclient/cluster_rm.go
This adds a new `--all` flag to cluster rm. It also requires a `--force` flag to remove a running cluster.
=> Remove all clusters

cli/cmd/customer_create.go, cli/cmd/runner.go, pkg/kotsclient/customer_create.go
```
$ ./bin/replicated customer create --channel Unstable --name "test from cli" --kots-install=false
Error: create customer: create customer: POST https://<redacted>/v3/customer 400: email is required for customers without kots install enabled
```
=> Support creating Helm CLI only customers

cli/print/channel_attributes.go, cli/print/channel_attributes_test.go, cli/print/channels.go, client/channel.go, pkg/kotsclient/channel.go, pkg/types/channel.go
Helm only release output:
```
$ replicated channel inspect Unstable
ID:             28ysVVeOzXzZVYRq8J7bBRAABWd
NAME:           Unstable
DESCRIPTION:    
RELEASE:        166
VERSION:        0.1.142
```
KOTS release output:
```
$ replicated channel inspect Beta
ID:             28ysVWYdIQZF1wPl548WIPM1ykJ
NAME:           Beta
DESCRIPTION:    Beta
RELEASE:        118
VERSION:        0.1.105
EXISTING:
curl -fsSL https://kots.io/install | bash
kubectl kots install test-kots/beta
EMBEDDED:
curl -fsSL https://k8s.kurl.sh/test-kots-beta | sudo bash
AIRGAP:
curl -fSL -o test-kots-beta.tar.gz https://k8s.kurl.sh/bundle/test-kots-beta.tar.gz
tar xvf test-kots-beta.tar.gz
sudo bash ./install.sh airgap
```
=> Don't show kots install commands for Helm channels

cli/cmd/release_create.go, cli/cmd/release_lint.go, cli/cmd/root.go
https://app.shortcut.com/replicated/story/80304/remove-is-foundation-app-flag
First in a series for this story: remove references to `app.IsFoundation` from CLI
vendor-api to follow in separate PR
=> Remove references to app.IsFoundation

cli/cmd/cluster_create.go, cli/cmd/cluster_kubeconfig.go, cli/cmd/cluster_ls.go, pkg/types/cluster.go
return human readable err when requesting kubeconfig for cluster not running
https://app.shortcut.com/replicated/story/82999/requesting-kubeconfig-for-cluster-not-running-should-provide-a-nicer-human-readable-error
=> feat: return human readable err when requesting kubeconfig for cluster not running 

cli/cmd/cluster_prepare.go, pkg/kotsclient/cluster_get.go
Fixes: `runPreflights`: Previously when preflights were run, all the analyzers were ignored. This fixes this and returns an error in case strict preflights are failing.
=> Fixing preflights for helm charts

cli/cmd/completion.go
Story details: https://app.shortcut.com/replicated/story/63726
Minor fix on help text alignment for `replicated completion --help`.  This fix was tested locally.
**Before**: 
```
Bash:
This script depends on the 'bash-completion' package.
If it is not installed already, you can install it via your OS's package manager.
$ source <(replicated completion bash)
```
**After**:
```
Bash:
This script depends on the 'bash-completion' package.
If it is not installed already, you can install it via your OS's package manager.
$ source <(replicated completion bash)
```
=> chore: [sc-63726] Fix text alignment for autocomplete help command

cli/cmd/cluster.go
The `cluster` subcommand is missing in the help output. Is that intentional? This PR adds it since c11y is public now.
```sh
[evans] $ replicated -h
The replicated CLI allows vendors to manage their apps, channels, releases and collectors.
Usage:
replicated [command]
Available Commands:
api         Make ad-hoc API calls to the Replicated API
app         Manage apps
channel     List channels
completion  Generate the autocompletion script for the specified shell
customer    Manage customers
enterprise  Manage enterprise channels, policies and installers
installer   Manage Kubernetes installers
login       Log in to Replicated
registry    Manage registries
release     Manage app releases
version     Print the current version and exit
Flags:
--app string     The app slug or app id to use in …
```
=> chore: show cluster subcommand in help

cli/print/clusters.go, pkg/types/cluster.go
```
$> replicated cluster versions                                                                         
Supported Kubernetes distributions and versions are:
DISTRIBUTION    VERSION                                                                                                            INSTANCE_TYPES
eks              1.22, 1.23, 1.24, 1.25, 1.26, 1.27                                                                                 m6i.large, m6i.xlarge, m6i.2xlarge, m6i.4xlarge, m6i.8xlarge
helmvm           1.27                                                                                                               r1.small, r1.medium, r1.large, r1.xlarge, r1.2xlarge
k3s              1.24, 1.25, 1.26 …
```
=> Adding instance types to cluster versions command

cli/cmd/cluster.go, cli/cmd/cluster_create.go, cli/cmd/cluster_kubeconfig.go, cli/cmd/cluster_ls.go, cli/cmd/cluster_prepare.go, cli/cmd/cluster_rm.go, cli/cmd/cluster_versions.go, cli/cmd/release_compatibility.go, cli/cmd/root.go, cli/cmd/runner.go, cli/print/release.go, pkg/kotsclient/release.go, pkg/kotsclient/release_compatibility.go, pkg/platformclient/client.go, pkg/types/release.go
Current output
```
$> ~/Projects/src/github/replicatedhq/replicated/bin/replicated release inspect 38                                                                                                             
Update available: v0.56.0
To upgrade, run "brew upgrade replicatedhq/replicated/cli"
SEQUENCE:    38
CREATED:     2023-08-17T22:13:42Z
EDITED:      0001-01-01T00:00:00Z
COMPATIBILITY RESULTS:
DISTRIBUTION    VERSION    SUCCESS_AT              SUCCESS_NOTES    FAILURE_AT              FAILURE_NOTES
k3s             1.26       -                                        2023-08-22T19:21:49Z    it does not work
kind            1.25.0     2023-08-22T19:20:49Z    it works also    -
CONFIG:
[{"name":"wordpress-enterprise-0.3.1.tgz","path":"wordpress-enterprise-.........
```
=> Adding c11y results to release inspect

cli/cmd/cluster_create.go, cli/cmd/cluster_upgrade.go, cli/cmd/root.go, cli/cmd/runner.go, pkg/kotsclient/cluster_create.go, pkg/kotsclient/cluster_upgrade.go, pkg/kotsclient/release_compatibility.go, pkg/types/cluster.go
```
$ replicated cluster upgrade --help
Upgrade a test clusters
Usage:
replicated cluster upgrade [cluster id] [flags]
Flags:
--dry-run          Dry run
-h, --help             help for upgrade
--output string    The output format to use. One of: json|table (default: table) (default "table")
--version string   Kubernetes version to upgrade to (format is distribution dependent)
--wait duration    Wait duration for cluster to be ready (leave empty to not wait)
Global Flags:
--app string     The app slug or app id to use in all calls
--token string   The API token to use to access your app in the Vendor API
```
=> feat (c11y): cluster upgrades

cli/cmd/cluster_upgrade.go
make consistent with `replicated cluster kubeconfig ID` command
=> fix (cmx): make cluster upgrade arg consistent

cli/cmd/cluster_create.go, cli/cmd/cluster_ls.go, cli/cmd/cluster_rm.go, cli/cmd/cluster_versions.go, cli/print/clusters.go, pkg/kotsclient/cluster_create.go, pkg/kotsclient/cluster_upgrade.go, pkg/kotsclient/release_compatibility.go, pkg/types/cluster.go
Next to doing a validation on number of nodes, it also fixes some other issues.
https://www.loom.com/share/cd576538ffa44be8a538f11c46d8b9df?sid=0839438f-8349-4a9e-8b92-cd92b5932f3a
=> Joshd/sc 88868/reject requests for vm clusters with 1 nodes

cli/print/clusters.go, pkg/types/cluster.go
Example for AKS:
```
DISTRIBUTION: aks
• VERSIONS: 1.27
• INSTANCE TYPES: Standard_B2ms, Standard_B4ms, Standard_B8ms, Standard_B16ms
• MAX NODES: 10
• ENABLED: false
• STATUS: unavailable
• DETAILS: Azure isn't having it today
```
=> Adding cluster distribution status

cli/cmd/cluster.go, cli/cmd/customer_inspect.go, cli/cmd/instance.go, cli/cmd/instance_inspect.go, cli/cmd/instance_ls.go, cli/cmd/instance_tag.go, cli/cmd/root.go, cli/cmd/runner.go, cli/print/instances.go, client/instance.go, pkg/kotsclient/cluster_create.go, pkg/kotsclient/instance.go, pkg/types/cluster.go, pkg/types/instance.go, pkg/types/tag.go
replicated instance ls/inspect/tag commands
```
$ ./bin/replicated instance ls --customer 2ULcKDT6snYYy5Zsdx3xuc3fffl 
ID                                      NAME      LAST ACTIVE                          VERSION    TAGS
7e5503f2-ba45-429f-8c94-6476d6d66fe5              2023-09-18 16:49:49.314 +0000 UTC    1.0.11     
2VOkWCw0nNp87r5qN6zcujzitm7             fozzy     2023-09-15 19:46:25.083 +0000 UTC    0.0.1      name=fozzy
1b1c5325-d06c-4ab3-8078-eafd07516b52    kermit    2023-09-11 15:08:00.138 +0000 UTC               manager=jim,name=kermit,type=frog
53359c21-0f94-4378-b0f1-2687fd8098d3              2023-08-23 17:36:15.531 +0000 UTC    0.1.2      
2ULcb51hPujG1L3bBcljP0avtCy             rolf      2023-08-22 16:55:08.013 +0000 UTC    0.1.2      manager=jim,name=rolf,type=dog,ui=yes2 …
```
=> Instance ls/inspect/tag CLI

cli/cmd/cluster_prepare.go
TL;DR
-----
Corrects file handling in `replicated cluster prepare`
Details
-------
Repairs a defect where `replicated cluster prepare` was leaving
the install script file open before executing it. I updated the
command to close the script file before running exec and made the
issue go away.
=> Fixes file busy command running KOTS install

cli/cmd/cluster_create.go, cli/cmd/cluster_ls.go, cli/cmd/cluster_update_ttl.go, cli/cmd/cluster_upgrade.go, cli/print/clusters.go, cli/print/util.go, pkg/types/cluster.go
Example:
```
> replicated cluster ls  --output wide
ID          NAME                           DISTRIBUTION    VERSION       STATUS          CREATED                          EXPIRES                          NODES    NODEGROUPS    TAGS
5742e99e    elastic_pare                   eks             1.29          provisioning    2024-02-14 17:46:30 +0000 UTC    -                                4        2
29e73446    affectionate_jepsen            k3s             1.29.0        running         2024-02-14 17:12:44 +0000 UTC    2024-02-14 18:15:01 +0000 UTC    1        1
```
=> Adding node and nodegroup count to output

cli/cmd/cluster_nodegroup.go, cli/cmd/cluster_nodegroup_ls.go, cli/cmd/root.go, cli/print/cluster_addons.go, cli/print/cluster_nodegroups.go, cli/print/clusters.go
Example output:
```
> replicated cluster nodegroup ls 190a93ec                                                                                                      
ID          NAME       DEFAULT    INSTANCE TYPE    NODES    DISK
c1955ee4    default    true       Standard_B2ms    1        50
4073a716    lkfsqe     false      Standard_B2ms    1        100
47124127    zrbwpm     false      Standard_B2ms    1        100
```
=> Adding nodegroup ls command

cli/cmd/customer_create.go, cli/cmd/runner.go, cli/print/customers.go, pkg/kotsclient/customer_create.go, pkg/types/customer.go
- Adds ability to create customer with a `custom-id`
- `customer ls` now displays `custom-id`
=> Add custom-id to customer create params

cli/cmd/cluster_create.go, cli/cmd/runner.go, pkg/kotsclient/cluster_create.go
Adds the ability to create Embedded Cluster clusters with the cli, for example:
```
replicated cluster create --distribution embedded-cluster --license-id ABCD1234
```
```
replicated cluster create --distribution embedded-cluster --license-id ABCD1234 --version 1.0.1
```
=> feat(cmx): add embedded-cluster distribution

cli/cmd/cluster_port.go, cli/cmd/cluster_port_expose.go, cli/cmd/cluster_port_ls.go, cli/cmd/cluster_port_rm.go, cli/cmd/root.go, cli/cmd/runner.go, cli/print/cluster_ports.go, cli/print/util.go, pkg/kotsclient/cluster_port_expose.go, pkg/kotsclient/cluster_port_list.go, pkg/kotsclient/cluster_port_remove.go, pkg/types/cluster.go
This adds the initial (hidden) implementation of port expose (and ls, rm) for CMX clusters.
=> Add cluster port command

pkg/platformclient/client.go
Include the value of the 'CI' environment variable in requests.
Most CI providers set this to "true" by default.
=> Include a header indicating if running from CI

cli/cmd/cluster_addon_ls.go, cli/print/cluster_addons.go, pkg/types/cluster.go
Adds s3 object store data to output.
```bash
$ replicated cluster addon ls 4d2f7e70
ID          TYPE            STATUS          DATA
d07cb204    Object Store    pending         {"bucket_prefix":"ethan"}
05929b24    Object Store    ready           {"bucket_prefix":"ethan","bucket_name":"ethan-05929b24-cmx","service_account_namespace":"cmx","service_account_name":"ethan-05929b24-cmx","service_account_name_read_only":"ethan-05929b24-cmx-ro"}
```
=> feat(cmx): expose addon object store data

cli/cmd/cluster_prepare.go, cli/cmd/customer_create.go, cli/cmd/customer_update.go, cli/cmd/root.go, cli/cmd/runner.go, client/customer.go, pkg/kotsclient/customer_create.go, pkg/kotsclient/customer_update.go, pkg/types/customer.go, pkg/types/entitlement.go
Adds the following fields to `customer create`:
```
IsEmbeddedClusterDownloadEnabled
IsGeoaxisSupported
IsHelmVMDownloadEnabled
IsIdentityServiceSupported
IsInstallerSupportEnabled
IsSupportBundleUploadEnabled
```
Adds the command `customer update`
=> Updating Customer CLI

pkg/kotsclient/release.go, pkg/kotsclient/release_test.go, pkg/types/release.go
For faster release promotions - excludes extraneous data in response object.
=> Add omit details to promote payload for faster release promotions

cli/cmd/app_delete.go, cli/cmd/app_ls.go, cli/cmd/root.go, client/app.go, client/client.go, pkg/kotsclient/app.go, pkg/kotsclient/app_test.go
During bootstrapping any command, CLI looks up application by listing all apps.  This can be slow for apps with a lot of channels and release. This change uses a query parameter currently supported by the API to not load unused channels data.
`replicated app ls --output json` still returns data will all channels.
=> Faster app lookup without channel data

cli/cmd/cluster_prepare.go, cli/cmd/customer_create.go, cli/cmd/customer_update.go, cli/cmd/runner.go, pkg/kotsclient/customer_create.go, pkg/kotsclient/customer_update.go, pkg/platformclient/client.go
Support creating multi-channel licenses
=> Support for creating multichannel licenses

cli/cmd/customer_create.go, cli/cmd/customer_update.go
No warning with 1 channel
```
$ ./bin/replicated customer create --name Geeglo --email zz2m8vguvo5n@geeglo.io --channel Stable --expires-in 720h --kots-install=false --output json --app app-create-test|jq
Update available: v0.79.0
To automatically upgrade, run "replicated version upgrade"
{
"id": "2kFaTZIyRm1mMieen35Gqcq46WO",
"customId": "",
"name": "Geeglo",
"email": "zz2m8vguvo5n@geeglo.io",
"channels": [
{
"id": "2YEfvli3H2BGqb2UvIZyw3JvHrL",
"name": "Stable",
"description": "",
"channelSlug": "stable",
"releaseSequence": 0,
"releaseLabel": "",
"isArchived": false,
"isHelmOnly": false
}
],
"type": "dev",
...
```
Warning with 2 channels, and `jq` still works
```
$ ./bin/replicated customer create --name Geeglo --email zz2m8vguvo5n@geeglo.io --channel Stable --channel Unstable …
```
=> Don't send error to stdout

cli/cmd/cluster_create.go, cli/cmd/cluster_create_test.go
None of the nodegroup fields are required.
=> make nodegroup fields optional

pkg/types/cluster.go
Part of [SC 110563](https://app.shortcut.com/replicated/story/110563/first-look-get-ssh-access-to-a-running-vm-kind-k3s-or-similar)
=> Expose overlay network

cli/cmd/customer_archive.go, cli/cmd/customer_create.go, cli/cmd/customer_download_license.go, cli/cmd/customer_inspect.go, cli/cmd/customer_ls.go, cli/cmd/customer_update.go, cli/cmd/root.go, cli/cmd/runner.go
Add short, long, examples.
Move vars out of the large runner.go file
=> Update the customer CLI

cli/cmd/cache_helper.go, cli/cmd/default.go, cli/cmd/default_clear.go, cli/cmd/default_clearall.go, cli/cmd/default_set.go, cli/cmd/default_show.go, cli/cmd/root.go, pkg/cache/app.go, pkg/cache/cache.go
Performance improvements:
- When we currently init the CLI on most commands, we hit the API to find the app. This introduces a cache where that API slug/id are stored.  there's no expiration on it right now, but these are immutable values generally?
Usability:
- Add a new "default" command:
`replicated default set app slackernews`
`replicated default show app`
`replicated default clear app`
These set the defaultApp value in the cache, so that we no longer need to pass it into every CLI function.
=> Cache and default app

cli/cmd/enterprise_portal_invite.go, cli/cmd/enterprise_portal_user.go, cli/cmd/enterprise_portal_user_ls.go, cli/cmd/root.go, pkg/kotsclient/enterprise-portal.go
replicated enterprise-portal invite
replicated enterprise-portal user ls
=> Adding invite commands to enterprise portal 

cli/cmd/release_create.go
Right now when go-git encounters an error we end up not printing a very useful error since it ends being unwrapped. e.g.
```
ERROR: reference not found
```
With this change we should bubble up a more detailed error that should more directly hint at the problem:
```
ERROR: git resolve revision '"HEAD"' failed: reference not found
```
=> bubble up more detailed git errors

cli/cmd/customer_download_license.go
I'm not 100% on the intentions behind switching away from setting the flags with `stringVar` but in doing so the flags weren't populating the variables used by the rest of the code. 
this patch populates the `var`s with the string values, but you could equally roll back to using `stringVar` and `stringVarp` instead.
=> Populate flag variables

cli/cmd/customer_download_license.go
Match code style from the other customer commands
=> Use stringVar(p) instead of manually populating variables

.github/workflows/release.yml, .goreleaser.yaml
Bump goreleaser to a modern version
=> Bump goreleaser to a recent version

dagger/release.go
Rename some variables.
Stop reusing the same error message.
And return true when it's ok.
=> Fix for git tree dirty

cli/cmd/cluster_create.go, cli/cmd/vm_create.go
For example:
```
❯ replicated vm create --distribution ubuntu foo bar
Error: unknown command "foo" for "replicated vm create"
```
=> Add noargs settings

dagger/release.go
Tell goreleaser what the last version was so it can generate change log correctly.
=> Set GORELEASER_CURRENT_TAG for goreleaser

cli/cmd/vm_ls.go, cli/print/clusters.go, cli/print/util.go, cli/print/vms.go, pkg/types/vm.go
```
ID          NAME                           DISTRIBUTION    VERSION       STATUS          CREATED                           EXPIRES                           COST
58de3692    affectionate_meitner           ubuntu          24.04         queued          2024-10-25 10:41 PDT              -                                 $0.60
88d71a2f    affectionate_meitner           ubuntu          24.04         queued          2024-10-25 10:41 PDT              -                                 $0.60
```
=> fix cost for vms

cli/cmd/customer_inspect.go
Fixes the --output flag in the `customer inspect` command.
=> Use correct output flag in customer inspect

dagger/release.go
Fetch last  release branch and use the last release tag to generate changelog.
=> Use last release tag and branch

dagger/release.go
```
• git state                                      commit=9a978c1cfb267543b95350f317766f52cc6d3f29 branch=release-0.83.12 current_tag=v0.83.11 previous_tag=v0.83.6 dirty=false
⨯ release failed after 0s                          error=git tag v0.83.11 was not made against commit 9a978c1cfb267543b95350f317766f52cc6d3f29
```
current_tag and previous_tag values are wrong when making next release:
```current_tag=v0.83.11 previous_tag=v0.83.6```
should be
```current_tag=v0.83.12 previous_tag=v0.83.11```
=> Use GORELEASER_PREVIOUS_TAG

pkg/version/github.go
```
$ replicated version upgrade
Error: download version: get release details: do request: Get "github.com/repos/replicatedhq/replicated/releases/tags/v0.83.12": unsupported protocol scheme ""
```
- Add `https://`
- Use `api.replicated.com`
=> Fix self-upgrade

dagger/release.go
`make build` can fail with the following error if ./bin/replicated is present and is corrupted in some way
```
Stderr:
command-line-arguments: go build command-line-arguments: build output "bin/replicated" already exists and is not an object file
make: *** [Makefile:106: build] Error 1
```
=> Remove ./bin/replicated from build container

cli/cmd/customer_inspect.go, pkg/kotsclient/channel.go, pkg/kotsclient/customer_list.go
Don't list all customers and app channels when running `replicated customer inspect` command.
1. First attempt to get customer by ID
2. If customer is not found, try using search API to search by name.
3. If there is only one match by name, get customer using the ID of the matching object.
=> Don't list all customers and channels for the customer inspect command

cli/cmd/cluster.go
Following #478 I caught another example which doesn't work, at the root of the `replicated cluster` command, it referenced the `nodegroup create` command which doesn't exist.  I changed the example to reference `nodegroup ls` for now since that actually does exist and will work.
=> chore(cmx): update cluster subcommand example to use nodegroup ls

cli/cmd/app_ls.go, cli/cmd/channel_ls.go, cli/cmd/channel_rm.go, cli/cmd/cluster_addon_ls.go, cli/cmd/cluster_addon_rm.go, cli/cmd/cluster_ls.go, cli/cmd/cluster_nodegroup_ls.go, cli/cmd/cluster_port_ls.go, cli/cmd/cluster_port_rm.go, cli/cmd/cluster_rm.go, cli/cmd/collection_ls.go, cli/cmd/collection_rm.go, cli/cmd/collector_ls.go, cli/cmd/customer_ls.go, cli/cmd/enterprise_portal_user_ls.go, cli/cmd/installer_ls.go, cli/cmd/instance_ls.go, cli/cmd/model_ls.go, cli/cmd/model_rm.go, cli/cmd/network_ls.go, cli/cmd/network_rm.go, cli/cmd/registry_ls.go, cli/cmd/registry_rm.go, cli/cmd/release_ls.go, cli/cmd/vm_ls.go, cli/cmd/vm_rm.go
These aliases are common across cli applications that get used in the same spaces as replicated, i.e: podman.
=> add common aliases

cli/cmd/cluster_addon_create_objectstore.go, cli/cmd/cluster_create.go, cli/cmd/runner.go
This adds a new flag to the `cluster create` command called `--addon`.  The addon flag is a `StringArrayVar` so it can be specified multiple times to add multiple types of addons, since we only support `object-store` at this time an example was added for that:
```
replicated cluster create --distribution eks --version 1.21 --nodes 3 --addon object-store --ttl 24h
```
Since addons share the arguments for `ClusterID`, `OutputFormat`, `Duration` and `DryRun` those all get inherited by values used in the `clusterCreate` command.
The only unique flag is `bucket-prefix` which has been added as an argument to `clusterCreate` with some validation added to ensure it is used when the `addons` array contains `object-store`.
I also refactored the existing args into runnerArgs so the args can more …
=> Support creating addons as part of 'cluster create' command

cli/cmd/default.go, cli/cmd/default_clear.go, cli/cmd/default_clearall.go, cli/cmd/default_set.go, cli/cmd/default_show.go, pkg/cache/cache.go
Fixes for `replicated default` command and subcommands:
- Enforce argument counts for positional arguments to avoid panics
- Check `defaultType` value before looking up application
- Add help text
=> Add help text for "replicated default" command

cli/cmd/channel_create.go, cli/cmd/channel_disable_semantic_versioning.go, cli/cmd/channel_enable_semantic_versioning.go, cli/cmd/enterpriseportal.go
Hide the Enterprise Portal command because the feature has not been released yet
Unhiding channel commands because they are supported for KOTS (despite what the comment on the removed lines says"
=> Hide enterprise and unhide channel commands

cli/cmd/customer_create.go, cli/cmd/customer_update.go, pkg/kotsclient/customer_create.go, pkg/kotsclient/customer_update.go
This adds `--helm-install` and `--kurl-install` flags to customer create and customer update commands.
Since we now support defining default customer values, these new flags will be omitted from the request if not specified in order to not override defaults. In order for these install types to be disabled, the explicit `=false` value must be specified on the command line. This is done for backwards compatibility with previous CLI releases.
https://app.shortcut.com/replicated/story/118967/add-support-for-install-types-when-creating-and-updating-customers-using-replicated-cli
=> Add support for install types when creating and updating customers

cli/cmd/cluster_addon.go, cli/cmd/cluster_addon_create_objectstore.go, cli/cmd/cluster_create.go, cli/cmd/network_create.go, cli/cmd/network_ls.go, cli/cmd/runner.go, cli/cmd/vm_create.go, cli/print/networks.go, pkg/kotsclient/network_create.go, pkg/kotsclient/network_get.go, pkg/kotsclient/vm_create.go, pkg/types/network.go
Create a new network:
```
❯ replicated network create --ttl 1h
ID          NAME                           STATUS          CREATED                           EXPIRES
dbb9101a    unruffled_johnson              queued          2025-01-22 10:07 PST              -
```
List all networks:
```
❯ replicated network ls
ID          NAME                           STATUS          CREATED                           EXPIRES
dbb9101a    unruffled_johnson              running         2025-01-22 10:07 PST              2025-01-22 11:08 PST
8c9792ac    optimistic_shockley            running         2025-01-22 09:57 PST              2025-01-22 11:04 PST
```
Create a new vm, reusing an existing network:
```
❯ replicated vm create --distribution ubuntu --network dbb9101a
ID          NAME …
```
=> Add network create cli support

docs/gen.go
Removes `Auto generated by spf13/cobra on ...` text from docs.
=> Don't include the auto-gen footer in docs

pkg/version/github.go, pkg/version/version.go
Removing `ErrTimeoutExceeded`.
- It was returned in multiple places, but never checked by the callers.
- It was expected by the caller in the only place where it wasn't returned.
So just use `os.IsTimeout` wherever needed.
=> Fix timeout error check

cli/cmd/network_update_outbound.go, pkg/kotsclient/network_update_outbound.go
When the Air Gap feature is not enabled:
```
❯ replicated network update outbound --id b649e7a6 --outbound none
Error: Air Gap is not enabled. Contact Replicated to get more information.
```
When the Air Gap feature is enabled:
```
❯ replicated network update outbound --id b649e7a6 --outbound none
ID          NAME                           STATUS          CREATED                           EXPIRES                           OUTBOUND
b649e7a6    lucid_cannon                   running         2025-01-31 09:43 PST              2025-01-31 10:43 PST              none
```
=> Add CMX Update Network outbound behind feature flag

cli/cmd/network_rm.go, cli/cmd/runner.go, pkg/kotsclient/network_rm.go
```
❯ rdev network create
ID          NAME                           STATUS          CREATED                           EXPIRES                           OUTBOUND
d0413567    blissful_spence                queued          2025-02-10 17:24 PST              -                                 -
❯ rdev network ls -w
ID          NAME                           STATUS          CREATED                           EXPIRES                           OUTBOUND
d0413567    blissful_spence                queued          2025-02-10 17:24 PST              -                                 -
d0413567    blissful_spence                assigned        2025-02-10 17:24 PST              -                                 -
d0413567    blissful_spence                provisioning    2025-02-10 17:24 PST …
```
=> Add network rm

cli/print/clusters.go, cli/print/vms.go, pkg/types/cluster.go, pkg/types/vm.go
The network column prints the short "network_id" affiliated with the VM or cluster.
```
$  replicated vm ls
ID          NAME                           DISTRIBUTION    VERSION       STATUS          CREATED                           EXPIRES                           COST
cef438fe    affectionate_wescoff           ubuntu          24.04         running         2025-02-19 11:40 PST              2025-02-19 15:40 PST              $0.88
$  replicated vm ls --output wide
ID          NAME                           DISTRIBUTION    VERSION       STATUS          CREATED                           EXPIRES                           COST           TAGS
cef438fe    affectionate_wescoff           ubuntu          24.04         running         2025-02-19 11:40 PST              2025-02-19 15:40 PST …
```
=> feature(cmx): add network column to 'vm ls' and 'cluster ls'

cli/cmd/root.go, cli/cmd/vm.go, cli/cmd/vm_scp.go, cli/cmd/vm_ssh.go, pkg/kotsclient/vm_common.go, pkg/kotsclient/vm_scp.go, pkg/kotsclient/vm_ssh.go
Currently SSH access to CMX VMs happens one of two ways:
- via the proxy
- In some scenarios this can cause high latency at the terminal
- directly
- but the user must fish out the ip and port number manually
This `replicated vm ssh` command handles connecting directly to a CMX vm via it's exposed port. 
it's behavior is such that: 
- specifying a VM by it's ID with `replicated vm ssh <id>` will connect you to that VM
- if no VMs are specified but multiple active VMs exist, prompt the user for which to connect to. 
TODO:
=> Add ssh and scp subcommand

cli/cmd/root.go, cli/cmd/version.go, pkg/version/updatecache.go, pkg/version/updatechecker.go, pkg/version/updateinfo.go, pkg/version/version.go
- Converted the blocking version update check to a non-blocking background operation
- Eliminated the 3+ second delay on every CLI command
- Added version cache invalidation to properly handle CLI upgrades
- Improved handling for development and "unknown" versions
- Added debug logging for version check diagnostics
Background Version Checking
- Moved the version check API call to a background goroutine that never blocks command execution
- Used existing cache (at ~/.replicated/cache.json) to store and retrieve update information
- Reduced the timeout for background checks from 3s to 1s
- Added proper cache management with version-specific invalidation
Development Version Handling
- Added special handling for "unknown" and development versions
- More gracefully handles semver parsing …
=> Performance Improvements for CLI Version Checking

.github/workflows/main.yaml, Dockerfile, dagger/docs.go, dagger/functionality.go, dagger/release.go
go.mod is now at 1.23, so we need to use 1.23
```
102 : [13.3s] | go build \
102 : [13.3s] |          \
102 : [13.3s] |         -tags "containers_image_ostree_stub exclude_graphdriver_devicemapper exclude_graphdriver_btrfs containers_image_openpgp" \
102 : [13.3s] |         -o bin/replicated \
102 : [13.3s] |         cli/main.go
102 : [13.4s] | go: go.mod requires go >= 1.23.0 (running go 1.22.12; GOTOOLCHAIN=local)
102 : [13.4s] | make: *** [Makefile:95: build] Error 1
```
=> Update all tools to use Go 1.23

cli/cmd/cluster_create.go, cli/cmd/cluster_ls.go, cli/cmd/cluster_nodegroup_ls.go, cli/cmd/cluster_port_expose.go, cli/cmd/cluster_port_ls.go, cli/cmd/cluster_port_rm.go, cli/cmd/cluster_update_nodegroup.go, cli/cmd/cluster_update_ttl.go, cli/cmd/cluster_upgrade.go, cli/cmd/network_create.go, cli/cmd/network_ls.go, cli/cmd/vm_create.go, cli/cmd/vm_ls.go, cli/cmd/vm_port_expose.go, cli/cmd/vm_port_ls.go, cli/cmd/vm_port_rm.go, cli/cmd/vm_update_ttl.go
Coming from kubectl, `-o` is a common alias for `--output`, update each of our uses of the `--output` command to a StringVarP so that the `-o` alias can be used for output format.
=> chore(cmx): accept `-o` for `--output`

cli/cmd/network_update_outbound.go
No json breakage:
```
./bin/replicated network update outbound --output json --id aeac7e86 --outbound none | jq
Note: 'replicated network update outbound' is deprecated. Use 'replicated network update policy' instead.
Updating policy to 'airgap' to match 'none' outbound setting
[
{
"id": "aeac7e86",
"name": "relaxed_moser",
"status": "running",
"created_at": "2025-03-18T21:17:45Z",
"expires_at": "2025-03-18T22:18:07Z",
"ttl": "1h",
"overlay_endpoint": "http://65.109.157.169:42151",
"overlay_token": "9c60a6694e9e30dcf461f71ca53a0034c36006bba6aa3741",
"policy": "airgap"
}
]
```
=> bug(cmx): Print to stderr to not break json

cli/cmd/vm_ssh.go, pkg/kotsclient/vm_ssh.go
Add `-i, --identity-file` support to the `vm ssh` command to allow a user to specify a custom identity file when using `replicated vm ssh`.
```
./bin/replicated vm ssh -i ~/.ssh/a-key-i-know-wont-work
✔ friendly_kalam (running)
The authenticity of host '[111.222.333.444]:42187 ([111.222.333.444]:42187)' can't be established.
ED25519 key fingerprint is SHA256:cyQAAVxafABejTt5GGt94nTChXLPiC23kFEzLQBIl6s.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[111.222.333.444]:42187' (ED25519) to the list of known hosts.
squizzi@111.222.333.444's password:
/bin/replicated vm ssh -i ~/.ssh/id_ed25519
✔ friendly_kalam (running)
$ 
./bin/replicated vm ssh -i ~/not-real
Error: identity file does not exist or …
```
=> feat(vm_ssh): support custom identity-file in 'vm ssh' command

.github/workflows/main.yaml
Update the github actions to run on `ubuntu-24.04`
Fixes https://app.shortcut.com/replicated/story/121844/update-actions-using-the-ubuntu-20-04-lts-runner
=> Pin action runner to `ubuntu-24.04` since 20.04 is EOLing

cli/cmd/customer_create.go, cli/cmd/customer_update.go, pkg/kotsclient/customer_create.go, pkg/kotsclient/customer_update.go
only send embeddedClusterDownloadEnabled and embeddedClustermultinodeenabled when they are set.  this avoid the following error:
```
ERROR: 400
METHOD: POST
ENDPOINT: https://api.replicated.com/vendor/v3/customer
is_embedded_cluster_multinode_enabled cannot be true if is_embedded_cluster_download_enabled is false
```
The problem is that embeddedClusterDownloadEnabled is true in the license policy, but the current CLI is sending false if i don't specify it.
=> Optionally send optional values

pkg/types/vm.go
Quick fix to make `disk_gib` a viewable entry in `vm ls -o json`
```
./bin/replicated vm ls -ojson
[
{
"id": "b1f451e6",
"name": "awesome_easley",
"distribution": "ubuntu",
"instance_type": "r1.small",
"version": "24.04",
"network_id": "596f0dba10e8a4bfa77e0552eb8aec4aca6ca81d676799eaf0fa4a70889990b2",
"disk_gib": 20, <---
"status": "running",
"created_at": "2025-05-06T20:56:28Z",
"expires_at": "2025-05-06T21:58:02Z",
"ttl": "1h",
"credits_per_hour": 9600,
"flat_fee": 50000,
"total_credits": 0,
"estimated_cost": 59600,
"direct_ssh_port": 45663,
"direct_ssh_endpoint": "65.109.157.169",
"tags": []
}
]
```
=> chore(cmx): Make disk_gib viewable in 'vm ls -o json'

cli/cmd/vm_endpoints.go, cli/cmd/vm_endpoints_test.go
This PR adds support for overriding the `GitHubUsername` value set in vendor-portal.  It can be overridden in the event that the username cannot be obtained from portal either for reason of error or simply the fact that the username is not populated.
* Added unit tests to the existing tests for `vm_endpoints`
* Manual testing:
Removed github username from vendor-portal:
```
./bin/replicated vm ssh-endpoint squizzi-ubuntu
Error: no GitHub account associated with Vendor Portal user
Visit the Account Settings page in Vendor Portal to link your account
Alternatively, you can use the --username flag to specify a custom username for the endpoint
Usage:
replicated vm ssh-endpoint VM_ID_OR_NAME [flags]
Example:
replicated vm ssh-endpoint aaaaa11
replicated vm ssh-endpoint my-test-vm
replicated vm …
```
=> feature(cmx): add ability to set custom username

pkg/types/vm.go
Add the `VMStatusVerifying` since VMs will soon enter this state prior to starting and on reboots.
=> chore(cmx): Add VMStatusVerifying to vm types

dagger/release.go
Bump go releaser to version v2.10.2 to attempt to resolve release failures due to Go 1.23 being used:
=> bump go release version

cli/print/clusters.go, cli/print/vms.go
It looks like the recent change made `LAST SCHEDULING STATUS` appear on the standard `vm ls` and `cluster ls` views when it was only supposed to end up on `-o wide`, this changes it to only appear on `-o wide`:
```
/bin/replicated vm ls
ID          NAME                           DISTRIBUTION    VERSION       STATUS          NETWORK      CREATED                           EXPIRES                           COST
84c623b3    charming_chatterjee            ubuntu          24.04         running         b4e76b9c     2025-07-09 11:20 PDT              2025-07-09 12:21 PDT              $0.60
./bin/replicated vm ls -owide
ID          NAME                           DISTRIBUTION    VERSION       STATUS          LAST SCHEDULING STATUS        NETWORK      CREATED                           EXPIRES …
```
=> chore(cmx): Make last scheduling status header only -o wide

cli/cmd/network_update.go, pkg/kotsclient/network_update.go
Prior to this change the API was responding (correctly) when `--collect-report` wasn't set because it was getting set to false and a non-nil check for the feature flag was firing which makes it so that policies cannot be set since they'll make the feature flag fire.
Before change, setting policy without collect report with the feature flag off for reporting would result in:
```
./bin/replicated network update 92ce6dab --policy open
Error: update network: Network Policy Reporting feature is not enabled. Contact Replicated to get more information.
```
With change, policy can be set:
```
./bin/replicated network update 92ce6dab --policy open
ID          NAME                           STATUS          CREATED                           EXPIRES                           POLICY …
```
=> fix(cmx): Use pointer for collect-report bool

cli/cmd/vm_port.go
Fix the help text for `replicated vm port --help`.
=> Update help text for vm port

cli/cmd/network_report.go, cli/print/network_reports.go
Before:
```
❯ r network report --id cec9ec1a -otable -w
CREATED AT           SRC IP          DST IP          SRC PORT DST PORT PROTOCOL COMMAND      PID      DNS QUERY       SERVICE
---
2025-08-13 19:25:17  10.0.0.11       95.217.220.251  13526    123      TCP      chronyd      833                      ntp
2025-08-13 19:25:17  10.0.0.11       95.216.100.21   53938    123      TCP      chronyd      833                      ntp
2025-08-13 19:25:18  10.0.0.11       162.159.200.1   65160    123      TCP      chronyd      833                      ntp
2025-08-13 19:25:19  10.0.0.11       162.159.200.123 62080    123      TCP      chronyd      833                      ntp
2025-08-13 19:26:07  10.0.0.11       216.58.209.164  37570    80       TCP      curl         1389     www.google.com  http …
```
=> Improve spacing network report output

cli/cmd/registry_rm.go, cli/cmd/registry_validate.go
Missed updating the doc string refs in https://github.com/replicatedhq/replicated/pull/574
=> Update rm/test help references to use `name`

cli/print/network_reports.go
This updates the `replicated network report` CLI so that it logs `-` in place of anything that is an empty string `""`.  Prior to this change we only logged `-` for fields that were empty ints.
For example:
Before:
```
2025-08-25 14:35 PDT                                    18881     53        UDP       -                -         replicated.com        dns
```
After:
```
2025-08-25 14:35 PDT  -                -                18881     53        UDP       -                -         replicated.com        dns
```
=> fix(network-report): Show dashes for all unpopulated fields

cli/cmd/vm_endpoints.go, cli/cmd/vm_endpoints_test.go
Allow to ssh or scp into a vm while the VM is in an updating state.
=> Allow ssh/scp while vm is updating

cli/cmd/network_report.go, cli/print/network_reports.go, pkg/kotsclient/network_report.go, pkg/types/network.go
Removes `created_at` for network reports, and replaces it with the timestamp field from the event data
Example output:
```
❯ rdev network report 2979703b -w
TIMESTAMP             SRC IP           DST IP           SRC PORT  DST PORT  PROTOCOL  COMMAND          PID       DNS QUERY             SERVICE
2025-09-17 11:03 PDT  10.0.0.11        216.58.210.164   63108     80        TCP       curl             1556      www.google.com        http
2025-09-17 11:03 PDT  10.0.0.11        216.58.210.164   63108     80        TCP       -                -         -                     http
2025-09-17 11:03 PDT  10.0.0.11        216.58.210.164   63108     80        TCP       curl             1556      www.google.com        http
2025-09-17 11:03 PDT  10.0.0.11        216.58.210.164   63108     80        TCP …
```
=> Do not show created at in the network report

cli/cmd/cluster_kubeconfig.go, cli/cmd/cluster_shell.go
We know `cluster.Status` but we don't use it in the error message, this makes it so that the error message becomes more useful:
```
./bin/replicated cluster kubeconfig 5c02712e
Error: cluster 5c02712e is not running, current status is provisioning
```
=> chore(cmx): Add current status in not running error
