replicatedhq/replicated

- .goreleaser.yml
- .travis.yml
- README.md
Add docker to travis environment.
> Configure goreleaser to generate homebrew formula [ch568]

- Makefile
- pkg/shipclient/release_test.go
> automatically generate the pact test version

- pacts/replicated-cli-vendor-graphql-api.json
- pkg/shipclient/release.go
- pkg/shipclient/release_test.go
Specifically `finalizeUploadedRelease` `allReleases` `lintRelease`
> add pact tests for ship queries

- .goreleaser.yml
- .travis.yml
- deploy/Dockerfile
> Add Dockerfile to build vendor-cli via goreleaser.

- pacts/replicated-cli-vendor-api.json
- pkg/platformclient/app_test.go
it requires a username, not an API token
> disable the 'delete app' pact

- Makefile
- pacts/replicated-cli-kots-vendor-graphql-api.json
- pkg/kotsclient/kotsclient_test.go
- pkg/kotsclient/release_test.go
this requires acting as a new pact consumer, unfortunately
> add a basic pact test for the kots client

- pkg/kotsclient/customer_list.go
- pkg/kotsclient/release.go
not just the first 20
fixes #156
> request all kots app licenses

- pkg/kotsclient/customer_list.go
this fixes a bug I introduced in #157 
Always make sure your working directory is clean, kids!
> Fix a fencepost error in the rewritten kots customer list code

- cli/cmd/collector_update.go
- cli/cmd/release_update.go
- client/channel.go
- pkg/enterpriseclient/client.go
- pkg/platformclient/app.go
- pkg/platformclient/channel.go
- pkg/platformclient/client.go
- pkg/platformclient/collector.go
- pkg/platformclient/errors.go
- pkg/platformclient/license.go
- pkg/platformclient/release.go
so we need to check for this too
> platform channel search returns ErrNotFound if not found, not gql error string

- cli/cmd/release_create.go
https://github.com/replicatedhq/replicated-starter-kots/blob/main/.github/workflows/main.yml#L36
> fix env var to match default in kots starter

- cli/cmd/release_create.go
- cli/cmd/runner.go
- Added ```--lint``` flag to ```replicated release create``` command 
- Adding ```--lint``` flag to ```--auto``` or ```--auto -y``` will set the lint-release value to true
> Javier add create lint auto

- pkg/kotsclient/channel.go
```Jelenas-MacBook-Pro-2:replicated jelenagruica$ ./bin/replicated channel ls
ID                             NAME          RELEASE    VERSION
1oIwGPJr1sCAk1CAOGnCB5wqv1k    Stable        15         0.0.1
1oIwGPYRrKbSCKLhYuXYgSi0PTp    Beta          16         0.0.1
1oIwGNjWvBmj2kRIpOjzf5vlD19    Unstable      15         0.0.1
1qGJiMM9aqbB1oWkaMLUWCS2IRH    JelenaTest    14         0.0.1
1qGKcaYRBeg6dRSVFcZG2FIho8R    JelenaTest    1          0.0.1
1qGKGIVLmpI3HBOOerdVkFYNa8j    JelenaTest    15         0.0.1
1qGKRKnFJ3XvwysbOMwN2QOohkm    JelenaTest    14         0.0.1
1qoIiSxrPwXhTVc9kQlJK6nPRuY    JelenaTest    14         0.0.1
Jelenas-MacBook-Pro-2:replicated jelenagruica$ ./bin/replicated release promote 17 1oIwGPJr1sCAk1CAOGnCB5wqv1k
Channel 1oIwGPJr1sCAk1CAOGnCB5wqv1k successfully …
```
> Nil pointer fix when promoting release

- .github/workflows/release.yml
- .goreleaser.yml
@dexhorthy not sure how to test this update to the GitHub action
> Updated goreleaser version to v1.5.0 to fix brew install issue.

- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/require-pr-labels.yml
- Dockerfile
- go.mod
- hack/Dockerfile.testing
Use reusable pact install action
> update pipelines to use reusable pact action

- .github/workflows/release.yml
* Install pact tooling in the release job for the deploy check
> install tooling in job

- cli/print/clusters.go
crashes with nothing otherwise
prototype code, that isn't going to main right now. feature branch to a longer running dev branch
> cluster ls: fix output

- cli/cmd/cluster_ls.go
- cli/cmd/runner.go
- pkg/kotsclient/cluster_list.go
Support for stopping and removing clusters, filtering terminated
> Filter and list clusters

- cli/cmd/cluster_create.go
- cli/cmd/cluster_kubeconfig.go
- cli/cmd/cluster_rm.go
- pkg/kotsclient/cluster_create.go
Return an error if an invalid/supported distribution or version was requested for c11y
> Return an error if an invalid cluster was created

- .github/workflows/release.yml
to handle inconsistent github behavior
> fix the release-support-ended script 

- cli/cmd/customer_archive.go
- cli/cmd/customer_create.go
- cli/cmd/customer_ls.go
- cli/cmd/release_create.go
- cli/cmd/release_promote.go
- cli/cmd/runner.go
- client/channel.go
- client/customer.go
- pkg/kotsclient/customer_list.go
This adds support for specifying the license type in the CLI when creating a license.
> Add support to specifying the license type when creating

- cli/cmd/cluster_create.go
> Rename field from vcpus to vcpu

- cli/cmd/cluster_create.go
and mark distribution and version as required
> Use a server supplied ttl default

- cli/cmd/customer_ls.go
modified:   cli/cmd/customer_ls.go
Change the --appversion flag to be --app-version instead
> As requested, change the --appversion flag to be --app-version instead

- cli/cmd/customer_inspect.go
- cli/cmd/root.go
- cli/cmd/runner.go
- cli/print/customer_attributes.go
- pkg/kotsclient/channel.go
- pkg/kotsclient/custom_hostname.go
- pkg/types/channel.go
- pkg/types/custom_hostname.go
- pkg/types/customer.go
https://app.shortcut.com/replicated/story/81196/cli-only-way-to-get-customer-helm-install-instructions
> Add CLI customer inspect command with helm instructions

- cli/cmd/release_create.go
https://app.shortcut.com/replicated/story/83432/allow-chart-flag-to-be-used-in-premium-accounts
> Allow --chart for premium user but include message

- .gitignore
- cli/cmd/cluster_prepare.go
- cli/cmd/root.go
- pkg/credentials/credentials.go
- pkg/replicatedfile/cache.go
- pkg/version/version.go
feat: 
- cache update checker info and build version 
- set cache ttl to 4 hours
- invalidate cache when
* current version is not cached version
* ttl expires 
chore: 
- update gitignore
- cleanup cluster prepare cmd helper
- switch to os package read/write
slack: https://replicated.slack.com/archives/C04T9AAMJUS/p1690383500550359?thread_ts=1690381446.326349&cid=C04T9AAMJUS
> cache update checker info

- cli/cmd/cluster_create.go
* Remove --distribution and --version default texts
* Capitalise texts to make them consistent
> chore: update "replicated cluster create -h" text

- cli/cmd/customer_archive.go
- cli/cmd/customer_download_license.go
- cli/cmd/customer_inspect.go
- cli/cmd/runner.go
- client/customer.go
- pkg/kotsclient/customer_list.go
Story details: https://app.shortcut.com/replicated/story/88051/replicated-cli-not-archiving-customers-by-name
This PR fixes a bug in `customer archive` command.  The bug does not accept customer name for the `archive` command.  This fix  allows the command to accept either the customer name or id as a parameter.
* Archive by customer name works: *
```
╭─siva@Sivas-Air ~/repos/replicatedhq/replicated/cli ‹siva/sc-88051/replicated-cli-not-archiving-customers-by●› 
╰─$ ./replicated customer ls      
ID                                             NAME             CHANNELS    EXPIRES    TYPE
2V2ayAUFgU58qnGNBQqEUBpMZr9    MyBigCustomer     Beta       Never      prod
╭─siva@Sivas-Air ~/repos/replicatedhq/replicated/cli ‹siva/sc-88051/replicated-cli-not-archiving-customers-by●› 
╰─$ ./replicated …
```
> Fix customer archive bug

- cli/cmd/cluster_ls.go
- cli/cmd/release_compatibility.go
- cli/print/clusters.go
- cli/print/util.go
With this PR, the output looks like:
```
ID          NAME                           DISTRIBUTION    VERSION       STATUS          CREATED                          EXPIRES
c4dc5a50    priceless_cannon               k3s             1.27.4        running         2023-09-06 19:01:46 +0000 UTC    2023-09-06 20:02:21 +0000 UTC
c3ad800f    stoic_napier                   k3s             1.24.16       running         2023-09-06 18:46:27 +0000 UTC    2023-09-06 19:47:19 +0000 UTC
f20541f1    quizzical_faraday              k3s             1.26.7        running         2023-09-06 18:33:41 +0000 UTC    2023-09-06 19:34:16 +0000 UTC
3a157ac6    nostalgic_mayer                k3s             1.25.12       running         2023-09-06 18:27:07 +0000 UTC    2023-09-06 19:27:56 +0000 UTC
98ba3f57 …
```
> Fixes the watch flag output

- cli/cmd/cluster_prepare.go
- cli/cmd/cluster_prepare_test.go
Only top level charts will be pushed.
> Ignore subcharts

- cli/cmd/cluster_create.go
- cli/cmd/cluster_prepare.go
- pkg/types/release.go
Makes version optional when using `cluster create` or `cluster prepare`
> Joshd/sc 89455/default cluster version for create

- pkg/platformclient/client.go
Adds some headers when detected that it's running in CI/GitHub Actions
> Add GitHub/CI info when in CI

- cli/cmd/release_create.go
Bad gzip file
```
$ ./bin/replicated release create --promote Stable --version 1.5.4 --chart ./some-test-file.txt 
...
• Reading chart from ./some-test-file.txt ✗
ERROR: gzip: invalid header
```
Valid gzip file, but not a valid chart
```
$ ./bin/replicated release create --promote Stable --version 1.5.4 --chart ./data.gz
...
• Reading chart from ./data.gz ✗  
ERROR: Chart.yaml file is missing
```
Valid chart, but not a valid release label
```
$ ./bin/replicated release create --promote Stable --version 1.5.4 --chart ./graphite/graphite-1.1.0.tgz
...
• Reading chart from ./graphite/graphite-1.1.0.tgz ✓  
• Creating Release ✓  
• SEQUENCE: 76
• Promoting ✗  
ERROR: 400
METHOD: POST
ENDPOINT: https://api.replicated.com/vendor/v3/app/<redacted>/release/76/promote
Version label does not match …
```
> Validate Helm chart before creating release

- cli/cmd/cluster_create.go
- cli/cmd/runner.go
- cli/print/clusters.go
- pkg/kotsclient/cluster_create.go
- pkg/types/cluster.go
adds --tag to the cluster create and output command
> Support for setting tags when creating a cluster

- cli/cmd/release_lint.go
Implements a TODO comment.
If a release only has Helm charts, it should use Builders linter.
> Use builders linter if release has charts only

- pacts/replicated-cli-vendor-api.json
- pkg/kotsclient/token_test.go
Tests for personal token and service account authentication using the /v3/clusters endpoint.
> Tests for token authentication

- pkg/platformclient/client.go
There is no `disable-kots` flag
> Fix flag in instructions

- cli/cmd/cluster_kubeconfig.go
- cli/cmd/cluster_shell.go
- cli/cmd/cluster_update_ttl.go
- cli/cmd/cluster_upgrade.go
- cli/cmd/root.go
- cli/cmd/runner.go
- go.mod
- go.sum
https://www.loom.com/share/c163466b98134bd5a65be76425a4df7b?sid=38d6903e-8830-4ec9-ab5e-1d3f87f9bec0
> Adding cluster shell command

- pkg/types/release.go
before:
```
$ ./bin/replicated release ls --output json | jq '.[0]'
{
"ActiveChannels": [
{
"id": "2aE1MkeefJypkriZgJfsCjc6nWN",
"name": "HelmBetaChannel",
"description": "",
"channelSlug": "",
"releaseSequence": 0,
"releaseLabel": "",
"isArchived": false,
"isHelmOnly": false
}
],
"AppID": "1YxE3W4Cy9Rlx3VseQNKyGTXdxC",
"CreatedAt": "2023-12-29T17:11:44Z",
"EditedAt": "0001-01-01T00:00:00Z",
"Editable": false,
"Sequence": 27,
"Version": "",
"Charts": null,
"IsHelmOnly": false
}
```
after:
```
$ ./bin/replicated release ls --output json | jq '.[0]'
{
"activeChannels": [
{
"id": "2aE1MkeefJypkriZgJfsCjc6nWN",
"name": "HelmBetaChannel",
"description": "",
"channelSlug": "",
"releaseSequence": 0,
"releaseLabel": "",
"isArchived": false,
"isHelmOnly": false
}
],
"appId": …
```
> BREAKING CHANGE: Add json tags to release type for JSON output

- cli/cmd/cluster_create.go
Will return exit code 124 in case the `--wait` flag is used and the cluster did not reach running status:
```
> replicated cluster create --distribution eks --wait 1m
ID          NAME                           DISTRIBUTION    VERSION       STATUS          CREATED                          EXPIRES    TAGS
f2317daa    bold_chatterjee                eks             1.28          provisioning    2024-01-17 00:56:52 +0000 UTC    -
> echo $?
124
```
> Return timeout exit code in case of wait duration exceeded

- cli/cmd/cluster_addon.go
- cli/cmd/cluster_addon_ingress.go
- cli/cmd/cluster_addon_ingress_create.go
- cli/cmd/cluster_addon_ls.go
- cli/cmd/cluster_addon_rm.go
- cli/cmd/cluster_shell.go
- cli/cmd/root.go
- cli/print/cluster_addons.go
- cli/print/clusters.go
- pkg/kotsclient/cluster_addon_rm.go
- pkg/kotsclient/cluster_addons_list.go
- pkg/kotsclient/cluster_ingress_create.go
- pkg/platformclient/client.go
- pkg/types/cluster.go
Initial CRUD support for managing ingresses in CMX VMs
> Add support for managing ingress in CMX

- cli/cmd/cluster_addon_ingress_create.go
- cli/cmd/runner.go
- pkg/kotsclient/cluster_ingress_create.go
- pkg/types/cluster.go
additional work on cmx ingress functionality
> CMX: ingress work

- cli/cmd/cluster_addon_ingress_create.go
- cli/print/cluster_addons.go
- pkg/kotsclient/cluster_addons_list.go
> cleaning up ingress

- cli/cmd/registry_add_gar.go
- cli/cmd/root.go
- pacts/replicated-cli-vendor-api.json
- pkg/kotsclient/registry_test.go
> Add registry - Google Artifact Registry

- pkg/kotsclient/cluster_port_remove.go
change path for deleting exposed cmx ports
> Fix path for deleting exposed ports

- pkg/types/cluster.go
> fix(cmx): no NodeGroup.ClusterID

- cli/cmd/cluster_shell.go
Story details: https://app.shortcut.com/replicated/story/98310
> fix: [sc-98310] Percent sign shows when exiting `shell`

- cli/cmd/collection.go
- cli/cmd/collection_create.go
- cli/cmd/collection_ls.go
- cli/cmd/collection_rm.go
- cli/cmd/model.go
- cli/cmd/model_ls.go
- cli/cmd/model_push.go
- cli/cmd/root.go
- cli/cmd/runner.go
- cli/print/ai-models.go
- pkg/kotsclient/collection_create.go
- pkg/kotsclient/collection_list.go
- pkg/types/ai-models.go
Some new commands, hidden for now.
`replicated model collections ls`
`replicated model collection create --name <param>`
> Create and list collections

- cli/cmd/collection_rm.go
- pkg/kotsclient/cluster_addon_rm.go
- pkg/kotsclient/collection_rm.go
> remove collection

- cli/cmd/cluster_update.go
- cli/cmd/cluster_update_nodegroup.go
- cli/cmd/cluster_update_ttl.go
- cli/cmd/root.go
- cli/cmd/runner.go
- pkg/kotsclient/cluster_update_nodegroup.go
Initial support for updating node groups.
The intent is to change an auto scaling group properties causing nodes to be replaced, validating more end customer environment issues.
> Add support for updating a node group

- pkg/ociclient/upload.go
Send content range headers for multi-part upload
> Properly send content-range header and support multi-part uploads

- cli/cmd/cluster.go
- cli/cmd/cluster_addon_create_postgres.go
- cli/cmd/cluster_addon_ls.go
- cli/cmd/cluster_addon_rm.go
- cli/cmd/cluster_kubeconfig.go
- cli/cmd/cluster_nodegroup_ls.go
- cli/cmd/cluster_port_expose.go
- cli/cmd/cluster_port_ls.go
- cli/cmd/cluster_port_rm.go
- cli/cmd/cluster_rm.go
- cli/cmd/cluster_shell.go
- cli/cmd/cluster_update.go
- cli/cmd/cluster_update_nodegroup.go
- cli/cmd/cluster_update_ttl.go
- cli/cmd/cluster_upgrade.go
https://www.loom.com/share/d40cf3501fa14216909656e3b4ffc1bf?sid=305716a3-aeb2-4421-b187-a2c6653b53f9
> Joshd/sc 108380/tab complete cluster ids

- cli/cmd/api_patch.go
- cli/cmd/root.go
- cli/cmd/runner.go
- pkg/kotsclient/api.go
```
$ ./bin/replicated api patch /v3/customer/2VffY549paATVfHSGpJhjh6Ehpy -b '{"name":"Valuable Customer"}' | jq
{
"customer": {
"id": "2VffY549paATVfHSGpJhjh6Ehpy",
"teamId": "-KeSmWDXkdYIV1ufGdoNkvAL3FCcyjq7",
"name": "Valuable Customer",
...
```
> Add api patch command

- pkg/kotsclient/channel.go
- pkg/kotsclient/channel_test.go
- pkg/types/channel.go
Use patch method for updating channels
> Use PATCH method to update channels

- cli/cmd/cluster.go
- cli/cmd/cluster_create.go
- cli/cmd/cluster_create_test.go
- cli/cmd/cluster_update.go
- cli/cmd/root.go
- cli/cmd/runner.go
- cli/cmd/vm.go
- cli/cmd/vm_create.go
- cli/cmd/vm_group.go
- cli/cmd/vm_group_ls.go
- cli/cmd/vm_ls.go
- cli/cmd/vm_nodegroup.go
- cli/cmd/vm_nodegroup_ls.go
- cli/cmd/vm_rm.go
- cli/cmd/vm_update.go
- cli/cmd/vm_update_ttl.go
- cli/cmd/vm_versions.go
- cli/print/vms.go
- pkg/kotsclient/vm_create.go
- pkg/kotsclient/vm_get.go
- pkg/kotsclient/vm_list.go
- pkg/kotsclient/vm_rm.go
- pkg/kotsclient/vm_update_ttl.go
- pkg/kotsclient/vm_versions.go
- pkg/types/vm.go
Adding
```
replicated vm create
replicated vm ls
replicated vm versions
replicated vm rm
replicated vm update ttl
replicated vm group ls
```
> Joshd/sc 113095/api cli changes for vms

- cli/cmd/customer_archive.go
- cli/cmd/root.go
- client/customer.go
- pkg/kotsclient/customer_list.go
- pkg/kotsclient/errors.go
Support for archiving a customer by ID , or multiple customers in a single CLI flag
> Archive customers

- cli/cmd/cluster_prepare.go
- cli/cmd/release_create.go
- cli/cmd/release_lint.go
- cli/cmd/release_update.go
- cli/cmd/root.go
This reverts commit 47573af7c49d307a109a77118c4d7f8efa7d146a.
> Revert "Deprecate --chart flag (#413)"

- .goreleaser.yaml
> Fix homebrew

- .gitignore
A place to keep local files so `make release` doesn't complain about git tree being dirty.
> Add local dir to gitignore

- dagger/release.go
> Fix syntax error

- cli/cmd/root.go
- cli/cmd/runner.go
- cli/cmd/vm_port.go
- cli/cmd/vm_port_expose.go
- cli/cmd/vm_port_ls.go
- cli/cmd/vm_port_rm.go
- cli/print/vm_ports.go
- pkg/kotsclient/cluster_port_expose.go
- pkg/kotsclient/vm_addon_rm.go
- pkg/kotsclient/vm_port_expose.go
- pkg/kotsclient/vm_port_list.go
- pkg/types/vm.go
[SC 115395](https://app.shortcut.com/replicated/story/115395/make-tunnels-work-on-cmx-vms)
> Joshd/sc 115395/make tunnels work on cmx vms

- cli/cmd/release_inspect.go
- cli/print/release.go
- Unhide release inspect
- Add support for --output flag
- Enforce number of arguments using Cobra
> Unhide release inspect command

- cli/cmd/release_download.go
Add more details to the release download command docs
> Fix docs for release download command

- cli/cmd/cluster.go
- cli/cmd/cluster_create.go
- cli/cmd/vm.go
- cli/cmd/vm_create.go
[SC 115244](https://app.shortcut.com/replicated/story/115244/some-minor-cmx-cli-improvements-based-on-feedback-autocomplete)
https://www.loom.com/share/aed36ae368a446769bf710fa564ade11?sid=0b3c1c6e-062d-4e86-8f04-dc4027fccd9e
> Add autocompletion for CMX distribution, version and instance type

- go.mod
- go.sum
> Bump go-getter v1.7.5 -> v1.7.6

- cli/cmd/runner.go
- cli/cmd/vm_port_expose.go
- cli/print/vm_ports.go
- pkg/kotsclient/vm_port_expose.go
- pkg/types/vm.go
Related PR: https://github.com/replicatedhq/vandoor/pull/7159
> fix:disable vm port expose for wildcard

- client/channel.go
In RBAC configurations where access to channel and releases is restricted, creating a release and promoting to a channel can fail when the channel is referenced by name instead of channel id. 
Sample RBAC policy that triggers this scenario:
```
{
"v1": {
"name": "Policy Name",
"resources": {
"allowed": [
"kots/app/some app id/list",
"kots/app/some app id/read",
"kots/app/some app id/channel/CHANNEL_ID_HERE/*",
"kots/app/some app id/channel/CHANNEL_ID_HERE/promote",
"kots/app/some app id/channel/CHANNEL_ID_HERE/update",
"kots/app/some app id/channel/CHANNEL_ID_HERE/read",
"kots/app/some app id/release/create",
"kots/app/some app id/release/*/read",
"kots/app/some app id/installer/read",
"user/token/create"
],
"denied": []
}
}
}
```
Example failure:
```
❯ …
```
> fix: allow promoting to channel by name when channel level rbac restrictions in place

- pkg/types/vm.go
Re: Slack Conversation https://replicated.slack.com/archives/C04T9AAMJUS/p1744028233981409
- Add InstanceType field to VM struct to support specifying VM instance types
> Add InstanceType field to VM struct

- cli/cmd/customer_create.go
- cli/cmd/customer_update.go
- pkg/kotsclient/customer_create.go
- pkg/kotsclient/customer_update.go
- pkg/types/customer.go
Related https://github.com/replicatedhq/vandoor/pull/7263
> feat(ec): api change to multi-node enabled

- cli/cmd/vm_create.go
`createVM` was expecting a `ErrWaitDurationExceeded`, where `waitForVM` was returning an ErrVMWaitDurationExceeded. Additionally, only info about running VMs was returned when the deadline was exceeded. This behaves differently than `waitForCluster` which prints out info about clusters that did not enter the running state.
This changes waitForVM to return the proper error when the deadline is exceeded as well as returning info about all VMs when that occurs. This helps provide better feedback to the user when their VMs fail to come up in the allotted time.
> fix(cmx): return proper error on vm deadline and print vm info

- go.mod
- go.sum
Update ulikunitz/xz to v0.5.15
https://github.com/ulikunitz/xz/issues/65
> Update ulikunitz/xz to v0.5.15
